# Configuracoes do Banco de Dados (HÍBRIDO - local + Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/estoque_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:010905Euja#}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracao da Porta (HÍBRIDO)
server.port=${SERVER_PORT:8083}
server.address=0.0.0.0

# Configuracoes de Seguranca
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER

logging.level.org.springframework.security=DEBUG

spring.security.enabled=false
management.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration